server:
  port: 8080

spring:
  application:
    name: Gestus
  docker:
    compose:
      file: C:\Users\lucas\OneDrive\Desktop\Projeto\GerenciadorTeatro\Gestus\Gestus\backend\compose.yaml

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  jwt:
    expiration: ${JWT_EXPIRATION:900000}
    key: ${JWT_KEY:Bh_JiU$0VsJ7C8vUJT63s8Q!0M31I6E4hv4MuEKZbOv4mbb7yVPFpkwIWJ#2m6Ye0AThLuFr1XZDeRLkalS_wI4lZn89wKHRU1ZrE2doKJ=rR&UIBtFj2M9BDGTU4ErikFIWmJByGipik0o5em6LuKcaftUgmMaqlWYaEzF=2!oD=CM18-RGUvAwk9WzRshPBvnVl#uVwe7JXV6WmAv9Vq5Y5lW&mkSVJ66RoksGlhfU1k4-&dx5q7-Jy1KK$zm7PF_dDQnZ1fzZX8jyZZNFZU28aHP36ykOVzKytkT3OXJ06sVKYMCYAVgfK#872v=rLmpwFjlwIlC0e7WLGSOxTyjT}



