server:
  port: ${PORT:10000}

spring:
  application:
    name: Gestus
  docker:
    compose:
      file: ./compose.yaml
  config:
    import: "optional:file:.env[.properties]"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:admin12345}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    show-sql: true

  jwt:
    expiration: ${JWT_EXPIRATION:900000}
    key: ${JWT_KEY}



